# Generated by Django 2.0.7 on 2018-07-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "screen_name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Screen name"
                    ),
                ),
            ],
            options={"db_table": "users"},
        )
    ]
