# Generated by Django 2.0.7 on 2018-07-27 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='TwitterAccount',
        ),
        migrations.AlterModelTable(
            name='twitteraccount',
            table='twitter_accounts',
        ),
    ]
