# Generated by Django 2.0.7 on 2018-07-28 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("users", "0004_friendship")]

    operations = [
        migrations.AlterField(
            model_name="friendship",
            name="twitter_account",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="users.TwitterAccount"
            ),
        )
    ]
