# Generated by Django 2.0.7 on 2018-07-28 10:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0005_auto_20180728_1030"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="friendship", unique_together={("user", "twitter_account")}
        )
    ]
