# Generated by Django 2.0.7 on 2018-07-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exposition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("ruby", models.CharField(blank=True, max_length=255, null=True)),
                ("short_name", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={"db_table": "expositions"},
        )
    ]
